# Renter tenancy {#part-1a-5}

This section summarizes research on period of stay in subsidized housing and any comparisons between tenancy in subsidized and unsubsidized housing.

## Research analysis

From a growing family to a change in employment, the length of time a person rents an apartment or home can vary depending on a multitude of factors. Little academic research has been conducted on the length of stay among market-rate renters. Most research conducted in this area is dedicated to better understanding apartment turnover rates from a commercial real estate perspective.

:::{.rmdnote}

To date, no formal research has been conducted making comparisons between market-rate and affordable housing resident length of stay. 

:::

For affordable housing residents, the most comprehensive study of length of stay was conducted in 2017 by the HUD’s Office of Policy Development and Research.[^Multi-Disciplinary Research Team. (2017). "Length of Stay in Assisted Housing." U.S. Department of Housing and Urban Development, Office of Policy Development and Research.] The report found that stays in affordable housing varied by program type. Housing Choice Voucher (HCV) program participants had a median stay of 4.8 years, while programs like public housing and Section 8 project-based programs had a median stay closer to market rate residents---three years.

LIHTC, a major source of affordable housing across the nation, was missing from this study, and no research was found to be conducted on LITHC tenant length of stay. However, Section 8 project-based assistance and HCVs are often tied to LIHTC units.

PDR notes that stays in affordable housing programs are likely to increase as market forces, such as rising home prices and stagnant wages, continue to negatively impact low-income households. This increased length of stay in affordable housing can prevent new residents from accessing a much needed resource when additional supply is not being generated. It can also be an indication of residents not being able to climb the economic ladder to move out of assisted housing. 

General consensus on market-rate rental housing tenancy ranges depending on whether a property is single-family or multifamily. Single-family rental stays average three years, while stays in multifamily properties averages about 27.5 months.[^ResidentRated.com. (2019). "Average U.S. Renter Stays in a Building 27.5 Months." ResidentRated.com. June 10, 2019. Retrieved from https://www.residentrated.com/blog/2019/6/10/average-us-renter-stays-in-a-building-275-months.] Affordable housing stays average higher at nearly six years, but can vary depending on household type. Senior households stay about nine years, while non-senior families with children stay about four years. 

For the private market, it can be beneficial to increase tenant length of stay. Tenant turnover can be costly for landlords who need to clean, repair, and market rental units. Vacancy, for any amount of time, equates to lost rent.

## Length of stay by tenure in Chesterfield

While there is no readily accessible dataset to compare length-of-stay between renters in subsidized versus market-rate housing, Table [B25038](https://censusreporter.org/data/table/?table=B25038&geo_ids=05000US51041&primary_geo_id=05000US51041) from the American Community Survey displays estimates for the year households moved into their current home by tenure.

The figure below shows this data for Chesterfield County using the latest 2016-2020 5-year estimates. Homeowners are much more likely to have lived in their home for a longer time than renters. Well over half of all homeowners last moved before 2009, with many settling in during the 2000-2009 decade. The majority of renters, on the other hand, moved into their current apartment in 2010 or after.

```{r length-of-stay, fig.cap="Percent of households by tenure by year moved into home"}

library(tidyverse)
library(tidycensus)
library(simplevis)
library(scales)

b25038_vars <- load_variables(2020, "acs5", cache = T) %>% 
  filter(str_detect(name, "B25038")) %>% 
  filter(str_detect(label, "Moved")) %>% 
  separate(label, into = c("est", "tot", "tenure", "moved"), sep = "!!") %>% 
  mutate(tenure = str_remove_all(tenure, " occupied:"),
         moved = str_remove_all(moved, "Moved in ")) %>% 
  select(name, tenure, moved)

b25038_raw <- get_acs(
  geography = "county",
  state = "VA",
  county = "Chesterfield County",
  variables = b25038_vars$name,
  year = 2020
)

b25038_data <- b25038_raw %>% 
  select(name = variable, estimate, moe) %>% 
  right_join(b25038_vars, by = "name") %>% 
  group_by(tenure) %>% 
  mutate(pct = estimate/sum(estimate)) %>% 
  ungroup() %>% 
  mutate(moved = gsub(" ", "\n", moved))

# b25038_plot <- ggplot(b25038_data, aes(x=moved, y=pct, fill=tenure)) +
#   geom_bar(stat = "identity") +
#   facet_wrap(~tenure) +
#   scale_y_continuous(labels=percent_format(accuracy=1, suffix="%")) +
#   theme(
#     axis.title.x = element_blank(),
#     axis.title.y = element_blank(),
#     legend.position = "none")
#   
# b25038_plot

gg_bar_col(b25038_data,
  x_var = moved,
  y_var = pct,
  col_var = tenure,
  y_labels = label_percent(),
  title = "Percent of households by tenure by year moved into home",
  y_title = "Percent of households",
  x_title = "Year moved into unit",
) +
  ggplot2::theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.justification = "center",
    legend.title = element_blank()
  )

```

*Source: U.S. Census Bureau, American Community Survey, 2016-2020 5-year estimates. Table B25038.*

## Takeaways

* Tenants may stay or leave in rental housing for various reasons regardless of the type of rental housing they call home.
* Longer lengths of stay mean economic stability for both tenant and landlord, but low turnover rates can exacerbate affordability challenges for new residents seeking to move to a community.
* With low turnover and minimal new rental construction, low supply leads to high demand across the rental market regardless of housing type.
* In Chesterfield County, renters in all types of units last moved much more recently than their homeowner counterparts.