# Ability-to-pay {#part-1b-4}

This section provides an analysis of homeowner and renter incomes versus the actual housing costs in Chesterfield County. This analysis seeks to determine the surplus and deficit of housing units by price. 

## Background

[reserved]

```{r global}

library(tidyverse)
library(tidycensus)
library(readxl)
library(lubridate)
library(optiRum)

```

## Homeowner affordability

[reserved]

```{r homeowner, eval=FALSE, include=FALSE}

years <- 2010:2020

b25119_vars <- load_variables(2010, "acs5") %>%
  filter(str_sub(name, end = 6) %in% "B25119")

b25119_raw <- map_dfr(years, function(yr){
  b25119_pull <- get_acs(
    geography = "county",
    county = "Chesterfield County",
    state = "VA",
    table = "B25119",
    year = yr
  ) %>%
    mutate(year = yr)
  })

b25119_vars_cleaned <- b25119_vars %>%
  separate(label, into = c("est", "income", "tenure"), sep = "!!") %>% 
  select(variable = name, tenure) %>%
  mutate(tenure = case_when(
    tenure == "Total" ~ "All households",
    tenure == "Owner occupied (dollars)" ~ "Homeowner",
    tenure == "Renter occupied (dollars)" ~ "Renter"
  ))

b25119_data <- b25119_raw %>%
  right_join(b25119_vars_cleaned, by = "variable") %>%
  select(NAME, year, tenure, estimate, moe) %>%
  group_by(year, tenure) %>%
  summarise(
    estimate = sum(estimate),
    moe = moe_sum(moe, estimate)
  ) %>% 
  ungroup() %>% 
  mutate(cv = ((moe/1.645)/estimate)*100) %>% 
  mutate(reliability = case_when(
    cv < 15 ~ "High reliability",
    cv >= 15 & cv <= 30 ~ "Medium reliability",
    cv > 30 ~ "Low reliability")
  )

cpi <- read_excel("data/CPI_U_RS.xlsx")
cpi <- cpi %>% 
  rename(year = Year,
         priceindex = Index) %>%
  transform(year = as.numeric(year))

b25119_cpi <- b25119_data %>%
    left_join(cpi, by = 'year') %>%
  transform(dollars20 = ((381.2/priceindex)*estimate)) %>%
  select(year, tenure, dollars20, moe, reliability) %>%
    filter(tenure == "Renter")

medsales <- read_csv("data/cvrmls_medsales.csv")

cpi_less <- read_csv("data/CUUR0000SA0L2.csv")

cpi_less$year <- floor_date(cpi_less$DATE, "year")

cpi_less <- cpi_less %>%
  rename(cpi_value = CUUR0000SA0L2) %>%
  transform(cpi_value = as.numeric(cpi_value))

annual_cpi_less <- cpi_less %>%
  group_by(year) %>%
  summarize(mean = mean(cpi_value))%>%
  mutate(year = as.integer(substring(year, 1,4)))

medsales_adjusted <- medsales %>% 
  left_join(annual_cpi_less, by = 'year') %>%
  rename(cpi = mean) %>%
  mutate(sales20 = ((235.67550/cpi)*medsales)) 

income_price <- b25119_cpi %>%
  left_join(medsales_adjusted, by = 'year') # Missing 2010 and 2011, as well as 2021-2022


# Assume $250/month for utilities
# Closing costs added to loan amount 

intrate <- .0442

income_price <- income_price %>%
  mutate(third =(dollars20 * .28)) %>%
  mutate(monthly = (third/12)) %>%
  mutate(canafford = PV((intrate/12), 360, (monthly * -1), 0)) # This is focusing in on 2020 median renter household income and 2020 median home price. 



chesterfield_jobs <- read_csv("data/chesterfield_wages_may2021.csv")

chesterfield_jobs <- chesterfield_jobs %>% # This is focusing on 2021 wages versus 2021 home price which was $330,000
  mutate(third =(meanannual * .28)) %>%
  mutate(monthly = (third/12)) %>%
  mutate(canafford = PV((intrate/12), 360, (monthly * -1), 0))

# Income needed to afford 2021 median sales price: $330,000

downpayment <- 330000 * .05
closingcosts <- loanamt * .015
intrate <- .0442
loanamt <- 330000 - downpayment + closingcosts

payment <- abs(PMT((intrate/12), 360, loanamt)) + 250

inc_needed <- ((payment*10)/2.8)*12

# Need a $78,935 to afford median home price


```

## Renter affordability
```{r rents}
rents <- read_xlsx("data/costar_rent_avg.xlsx")


```

```{r renteraffordability}
chesterfield_jobs <- chesterfield_jobs %>% # 2021 Rent was $1,420 adjusted for inflation already
  mutate(rent = (third/12))


```

[reserved]

## Takeaways

[reserved]