# Route 1 affordability analysis  {#part-1b-5}

The northern section of U.S. Route 1 in Chesterfield County has . . .

```{r global}

library(tidyverse)
library(tidycensus)
library(readxl)
library(optiRum)
library(lubridate)
library(stringi)
library(ggplot2)
library(plotly)

```

## Study area

Census tracts 1003, 1004.03, 1004.04, 1004.05, 1004.06, 1004.07, 1004.09 all border Route 1 from Northern Chesterfield to Route 10.

[base map]

[description]

## Homeowner affordability

[reserved]

```{r homeprices}

r1_sales <- read_csv("data/routeone_mls.csv")

r1_sales$salesdate <- mdy(r1_sales$salesdate)

r1_sales$year <- floor_date(r1_sales$salesdate, "year")

r1_sales$salesprice <- as.numeric(gsub('[\\$|,]','', r1_sales$salesprice))

medsales <- r1_sales %>%
  filter(status != "ACT") %>%
  group_by(year) %>%
  summarise(median = median(salesprice))
  
```

```{r homeowneraffordability}
r1_jobs <- read_csv("data/routeone_otm_may2021.csv")

# Compare to $251,000 sales price
# As of 4.1.22 - current rate for Virginia Mortgage is 4.83% via BankRate.com
# Assume $250/month for utilities
# Closing costs added to loan amount 

downpayment <- 251000 * .05
closingcosts <- loanamt * .015
intrate <- .0442
loanamt <- 251000 - downpayment + closingcosts

payment <- abs(PMT((intrate/12), 360, loanamt)) + 250

inc_needed <- ((payment*10)/2.8)*12

# Route One residents need to make approximately $60,980/year to afford the median sale price.

r1_jobs$meanannual <- as.numeric(gsub('[\\$|,]','', r1_jobs$meanannual))

r1_jobs <- r1_jobs %>% 
  mutate(third = (meanannual * .28)) %>%
  mutate(monthly = (third/12) - 250 )

r1_jobs <- r1_jobs %>%
  mutate(canafford = PV((intrate/12), 360, (monthly * -1), 0))

```

```{r route1, eval=FALSE, include=FALSE}

years <- 2010:2019

b25119_vars <- load_variables(2010, "acs5") %>%
  filter(str_sub(name, end = 6) %in% "B25119")

b25119_raw <- map_dfr(years, function(yr){
  b25119_pull <- get_acs(
    geography = "tract",
    county = "Chesterfield County",
    state = "VA",
    table = "B25119",
    year = yr,
    survey = "acs5"
  ) %>%
    mutate(year = yr)
  })

b25119_vars_cleaned <- b25119_vars %>%
  separate(label, into = c("est", "income", "tenure"), sep = "!!") %>% 
  select(variable = name, tenure) %>%
  mutate(tenure = case_when(
    tenure == "Total" ~ "All households",
    tenure == "Owner occupied (dollars)" ~ "Homeowner",
    tenure == "Renter occupied (dollars)" ~ "Renter"
  ))

b25119_data <- b25119_raw %>%
  right_join(b25119_vars_cleaned, by = "variable") %>%
  select(NAME, year, tenure, estimate, moe) %>%
  group_by(year, NAME, tenure) %>%
  summarise(
    estimate = sum(estimate),
    moe = moe_sum(moe, estimate)
  ) %>% 
  ungroup() %>% 
  mutate(cv = ((moe/1.645)/estimate)*100) %>% 
  mutate(reliability = case_when(
    cv < 15 ~ "High reliability",
    cv >= 15 & cv <= 30 ~ "Medium reliability",
    cv > 30 ~ "Low reliability")
  )

cpi <- read_excel("data/CPI_U_RS.xlsx")
cpi <- cpi %>% 
  rename(year = Year,
         priceindex = Index) %>%
  transform(year = as.numeric(year))

route1 <- c("Census Tract 1003", "Census Tract 1004.03", "Census Tract 1004.04", "Census Tract 1004.05",
         "Census Tract 1004.06", "Census Tract 1004.07","Census Tract 1004.09")

b25119_cpi <- b25119_data %>%
    left_join(cpi, by = 'year') %>%
  transform(dollars19 = ((376.5/priceindex)*estimate)) %>%
  select(year, NAME, tenure, dollars19, moe, reliability) %>%
  separate(NAME, into = c("tract", "county", "state"), sep = ",") %>%
  select(year, tract, tenure, dollars19, moe, reliability)

route1_tracts <- b25119_cpi %>%
  subset(tract %in% route1)



# Reserved for Shiny app
```

## Renter affordability

[reserved]

```{r rents}
r1_rents <- read_csv("data/routeone_avgrent.csv")

avgrent <- ggplot(r1_rents, aes(x=year, y=askingrent)) +
  geom_line()

ggplotly(avgrent)

```

```{r renteraffordability}
r1_jobs <- r1_jobs %>% 
  mutate(rent = (third/12))


```
## Takeaways

[reserved]