# Outreach

This section summarizes interviews and additional outreach with non-profit and for-profit multifamily developers with existing or prospective projects in the county. 

## Process

To gather additional details on the state of Chesterfield County's rental market, a total of ___ persons from ___ organizations were interviewed in early June 2022. These interviews collected input from:

* For-profit multifamily and mixed use developers,
* Nonprofit multifamily developers and property managers, and
* Commercial real estate brokers focused on multifamily and mixed use properties.

Specific interview topics and questions varied, but were organized around the prevalent trends, challenges, and opportunities found today in the county's rental market.

## Trends

All interviewees strongly agreed that the demand for rental housing in the county far exceeds the current supply. One individual stated that the market has "shot straight up"---and that the county will only get more expensive in the near future. Recent interest rate increases may cool the pace of new development, along with pricing out homebuyers with marginal incomes. Together, these symptoms would place additional rental demand on an already limited supply.

The growing demand for rental homes can be attributed to many different household types, but respondents noted several important groups. First, families with one or more children, but with incomes too low to purchase a home, are looking for apartments with three or more bedrooms. County schools are often a motivator, as interviewees noted anecdotal increases in households moving from the City of Richmond and the Tri-Cities areas. Due to their higher childcare and other household costs, these families need an affordable rent to balance their budgets.

::: {.rmdnote}

Property managers of affordable rental communities stated that current waitlists for apartments range from 30 to more than 100 applicants. 

:::

Second, there is an acute need for more senior and age-restricted homes, particularly options that are affordable to those on low and/or fixed incomes. These residents have aged out of their previous home due to maintenance or accessibility issues. Finally, among renters who are currently being served by new Class A development, most are one- or two-person households moving into the area to work from home, or are long-term county residents willingly downsizing from a larger home.

## Challenges

Interviewees described a range of obstacles preventing the creation of new rental homes to meet demand. These challenges focus on market conditions, development regulations, and changing attitudes about rental housing.

First, respondents shared that new development has gotten more difficult due to increasing acquisition, material, and labor costs. These trends are currently found in nearly every part of the nation, as well. Among existing properties, Class A, B, and C multifamily assets are all "performing very well," which demonstrates demand from a wide range of incomes.

However, owners of lower cost, market-affordable rental properties (NOAH) have been less willing to sell their assets, which could lead to revitalization in certain areas, as well as continued preservation of attainable housing options. These long-term, local owners are hesitant to deal with the selling process, and are tax averse with respect to capital gains.

In areas where property values may be lower, prevailing market and community conditions can make development unfavorable. The northern Route 1 corridor was noted as an important example: despite its proximity to downtown Richmond and I-95, crime issues were repeatedly noted as a turn-off for developers. Furthermore, several interviewees stated that the low incomes found along that corridor would not support new market-rate development.

Second, various development regulations were listed as challenges imposed by the county.

- 8 out of 10 calls (to broker) are from pure multifamily developers who don't do mixed use
- Expectation for first-floor commerical component can make financing difficult (standalone multifamily is easier)
- Utility connection and permit fees can be high relative to other localities, along with road proffers

Finally, nearly all respondents mentioned increasing public and political concern about new rental housing, particularly focused on apartments using public subsidy to serve lower incomes.

- Increasing political obstructions for affordable rental housing development, especially along Route 1 ("victim of its own success" following some successful developments)

## Opportunities

Affordable
- Getting sites designated by county as "revitalization areas" helps with LIHTC scoring, practice should continue
- Even small amounts of tax abatement from county would increase LIHTC scoring
- Despite some opposition, citizens and residents will demonstrate support for new affordable rental housing
- Continued rental development in areas served by GRTC is ideal

Corridors
- Hull Street likely to continue performing better than Route 1 (less of a "stigma" and strong western component)
- Hull Street seeing more activity/interest, will continue to grow organically like Midlothian Turnpike
- Chance to revive/reuse vacant commercial space in Route 1 / Chester / I-95 area
- County would need to provide meaningful incentives to attract market-rate development in northern Route 1

