# (PART) CORRIDOR CASE STUDIES {.unnumbered}

# Route 1 corridor analysis {#part-2b-1}

This section describes the Route 1 corridor in terms of its rental housing market, proximity of rental homes to amenities, recent major investments, and homeownership relative to the price of single-family rentals.

The Route 1 corridor used in this section uses the same six census tracts from the previous Route 1 affordability analysis in [Chapter 10](#part-1b-5).

## Rental housing supply

### Number of rental homes

- ACS estimate of renter households
- CoStar number of apartments (all types)
- Manufactured home communities
- Estimated single-family rentals (county data)

### Rental prices

- ACS median rent by tract
- CoStar average asking rent (all units)
- CoStar average asking rent (by bedroom)
- Single-family home rents (active listings and units leased in past 365 days, via MLS)

### Conditions

- ACS rental units by year built
- CoStar property year built
- CoStar rating
- MHC ratings from 2016 MHCCV study

## Proximity to amenities

### Public transportation

Compare location of new multifamily development versus older multifamily relative to access to public transportation

- Within or outside of 1/2 mile buffer from GRTC stop

### Schools

Compare location of new multifamily development versus older multifamily relative to access to public schools

- Within or outside of 30 minute drive time

### Grocery stores

Compare location of new multifamily development versus older multifamily relative to access to grocery stores

- Within or outside of 1/2 mile buffer from grocery store

### Healthcare

Compare location of new multifamily development versus older multifamily relative to access to hospitals and urgent care facilities

- Within or outside of 15 minute drive time

### Job centers

TBD, waiting for feedback from county staff

## Public and private investments

- Check CoStar for newest builds/renovations/transactions (commercial properties, too)
- Ask Jessica for what county has had a hand in

Route 10, Bermuda Estates, Falling Creek Rehab, Multifamily Overlay District, R.O.A.R.

### Case study

- Choose an interesting recent residential development
- Add a photo
- Describe development and market it serves
- Rent/sale prices

## Single-family rental versus purchase

- Single-family rental prices from MLS records
- Median home sales price from past 365 days
- Calculate income needed to afford SFR and homeownership
- Use same methodology from Part 1b-4 for homeownership affordability
