# Measures of housing affordability {#part-1a-2}

This section will summarize the common measures of housing affordability that are widely used by researchers and policymakers, as well as credible alternative measures. Comparisons are made of each measure using county-specific data to understand the variations.

## Background

Determining what housing is affordable and to whom is a key challenge many communities face as housing prices continue to rise. For many researchers and practitioners, the 30 percent of income ratio has been the standard measure due to its ease in application and understanding among the public. But criticism laid upon this measure points to its failure to account for the varying differences in cost of living based on household size and location.

Other measures have gained credibility over time such as the Housing Affordability Index (HAI) from the National Association of REALTORS and the Housing Wage from the National Low Income Housing Coalition (NLIHC). Alternative measures such as the residual income approach and the Housing and Transportation Affordability Index from the Center for Neighborhood Technology have been gaining traction.

## Affordability measure comparisons

The following summarizes select standard and alternative measures and provides an understanding of affordability within a Chesterfield County-specific context.

| Measure                                 | Method                                                                                                                  | Pros | Cons |
|-----------------------------------------|-------------------------------------------------------------------------------------------------------------------------|------|------|
| 30 percent standard                     | No more than 30 percent of household income is spent on housing costs                                                   |      |      |
| NAR's Housing Affordability Index (HAI) | Comparision of whether a household can afforda a mortgage loan for a typical home                                       |      |      |
| NLIHC's Housing Wage                    | Hourly wage full-time worker must earn to afford fair market rent without spending more than 30 percent of their income |      |      |
| Residual income approach                | Income after non-housing costs determines the price of housing that is affordable to households                         |      |      |
| CNT's H+T Affordability Index           | No more than 45 percent of household is spent on housing and transportation costs combined                              |      |      |

## Takeaways

[reserved]
