<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 10 Route 1 affordability analysis | Chesterfield County Rental Market Analysis</title>
<meta name="author" content="HDAdvisors">
<meta name="description" content="This section provides a focused analysis of housing affordability along the U.S. Route 1 corridor in Chesterfield County from the county-city border to the north down to Route 10 at the southern...">
<meta name="generator" content="bookdown 0.26 with bs4_book()">
<meta property="og:title" content="Chapter 10 Route 1 affordability analysis | Chesterfield County Rental Market Analysis">
<meta property="og:type" content="book">
<meta property="og:description" content="This section provides a focused analysis of housing affordability along the U.S. Route 1 corridor in Chesterfield County from the county-city border to the north down to Route 10 at the southern...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 10 Route 1 affordability analysis | Chesterfield County Rental Market Analysis">
<meta name="twitter:description" content="This section provides a focused analysis of housing affordability along the U.S. Route 1 corridor in Chesterfield County from the county-city border to the north down to Route 10 at the southern...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><script src="libs/plotly-binding-4.10.0/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<link rel="stylesheet" href="bs4_book.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Chesterfield County Rental Market Analysis</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">About</a></li>
<li class="book-part">LITERATURE REVIEW</li>
<li><a class="" href="part-1a-1.html"><span class="header-section-number">1</span> Planning for housing in Chesterfield County</a></li>
<li><a class="" href="part-1a-2.html"><span class="header-section-number">2</span> Measures of housing affordability</a></li>
<li><a class="" href="part-1a-3.html"><span class="header-section-number">3</span> Market-affordable housing</a></li>
<li><a class="" href="part-1a-4.html"><span class="header-section-number">4</span> Concentrations of affordable housing</a></li>
<li><a class="" href="part-1a-5.html"><span class="header-section-number">5</span> Renter tenancy</a></li>
<li class="book-part">DEMOGRAPHIC AND AFFORDABILITY ANALYSIS</li>
<li><a class="" href="part-1b-1.html"><span class="header-section-number">6</span> Data sources and reliability</a></li>
<li><a class="" href="part-1b-2.html"><span class="header-section-number">7</span> Household income</a></li>
<li><a class="" href="part-1b-3.html"><span class="header-section-number">8</span> Household cost burden</a></li>
<li><a class="" href="part-1b-4.html"><span class="header-section-number">9</span> Ability-to-pay</a></li>
<li><a class="active" href="part-1b-5.html"><span class="header-section-number">10</span> Route 1 affordability analysis</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/hdadvisors/chesterfield-market-analysis">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="part-1b-5" class="section level1" number="10">
<h1>
<span class="header-section-number">10</span> Route 1 affordability analysis<a class="anchor" aria-label="anchor" href="#part-1b-5"><i class="fas fa-link"></i></a>
</h1>
<p>This section provides a focused analysis of housing affordability along the U.S. Route 1 corridor in Chesterfield County from the county-city border to the north down to Route 10 at the southern end.</p>
<div id="background-8" class="section level2" number="10.1">
<h2>
<span class="header-section-number">10.1</span> Background<a class="anchor" aria-label="anchor" href="#background-8"><i class="fas fa-link"></i></a>
</h2>
<p>The northern section of U.S. Route 1 in Chesterfield County saw substantial economic activity throughout the middle of the 20th century. As the major north-south interstate corridor along the East Coast, American motorists stopped at the many motels and food stops that sustained a vibrant tourist economy.</p>
<p>However, the creation of Interstate 95 in the late 1950s drew traffic, and with it business, away from the Route 1 corridor. Throughout the latter half of the 20th century, the corridor saw decline and significant changes that presented challenges for revitalization efforts.</p>
<p>A growing Hispanic population along the corridor has helped reignite commercial activity along the corridor, but housing challenges still exist. Although one of the most affordable areas in Chesterfield County, the corridor has remained generally affordable due to older housing units—many of which are out of style and in need of significant rehabilitation.</p>
</div>
<div id="study-area" class="section level2" number="10.2">
<h2>
<span class="header-section-number">10.2</span> Study area<a class="anchor" aria-label="anchor" href="#study-area"><i class="fas fa-link"></i></a>
</h2>
<p>For the purposes of this analysis, the study area is defined as the Census tracts 1003, 1004.04, 1004.05, 1004.06, 1004.07, 1004.09. These tracts all border Route 1 from Northern Chesterfield to Route 10.</p>
<pre><code>#&gt; 
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |                                                                      |   1%
  |                                                                            
  |=                                                                     |   1%
  |                                                                            
  |=                                                                     |   2%
  |                                                                            
  |==                                                                    |   2%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |===                                                                   |   4%
  |                                                                            
  |===                                                                   |   5%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |=====                                                                 |   8%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=======                                                               |   9%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |=======                                                               |  11%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |=========                                                             |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |=========                                                             |  14%
  |                                                                            
  |==========                                                            |  14%
  |                                                                            
  |==========                                                            |  15%
  |                                                                            
  |===========                                                           |  15%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |============                                                          |  17%
  |                                                                            
  |============                                                          |  18%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |==============                                                        |  19%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |==============                                                        |  21%
  |                                                                            
  |===============                                                       |  21%
  |                                                                            
  |===============                                                       |  22%
  |                                                                            
  |================                                                      |  22%
  |                                                                            
  |================                                                      |  23%
  |                                                                            
  |================                                                      |  24%
  |                                                                            
  |=================                                                     |  24%
  |                                                                            
  |=================                                                     |  25%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |==================                                                    |  26%
  |                                                                            
  |===================                                                   |  26%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |===================                                                   |  28%
  |                                                                            
  |====================                                                  |  28%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=====================                                                 |  29%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |=====================                                                 |  31%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |=======================                                               |  32%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |=======================                                               |  34%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |=========================                                             |  35%
  |                                                                            
  |=========================                                             |  36%
  |                                                                            
  |==========================                                            |  36%
  |                                                                            
  |==========================                                            |  37%
  |                                                                            
  |==========================                                            |  38%
  |                                                                            
  |===========================                                           |  38%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |============================                                          |  39%
  |                                                                            
  |============================                                          |  40%
  |                                                                            
  |============================                                          |  41%
  |                                                                            
  |=============================                                         |  41%
  |                                                                            
  |=============================                                         |  42%
  |                                                                            
  |==============================                                        |  42%
  |                                                                            
  |==============================                                        |  43%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |===============================                                       |  45%
  |                                                                            
  |================================                                      |  45%
  |                                                                            
  |================================                                      |  46%
  |                                                                            
  |=================================                                     |  46%
  |                                                                            
  |=================================                                     |  47%
  |                                                                            
  |=================================                                     |  48%
  |                                                                            
  |==================================                                    |  48%
  |                                                                            
  |==================================                                    |  49%
  |                                                                            
  |===================================                                   |  49%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |===================================                                   |  51%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |====================================                                  |  52%
  |                                                                            
  |=====================================                                 |  52%
  |                                                                            
  |=====================================                                 |  53%
  |                                                                            
  |=====================================                                 |  54%
  |                                                                            
  |======================================                                |  54%
  |                                                                            
  |======================================                                |  55%
  |                                                                            
  |=======================================                               |  55%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |========================================                              |  56%
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |========================================                              |  58%
  |                                                                            
  |=========================================                             |  58%
  |                                                                            
  |=========================================                             |  59%
  |                                                                            
  |==========================================                            |  59%
  |                                                                            
  |==========================================                            |  60%
  |                                                                            
  |==========================================                            |  61%
  |                                                                            
  |===========================================                           |  61%
  |                                                                            
  |===========================================                           |  62%
  |                                                                            
  |============================================                          |  62%
  |                                                                            
  |============================================                          |  63%
  |                                                                            
  |=============================================                         |  64%
  |                                                                            
  |=============================================                         |  65%
  |                                                                            
  |==============================================                        |  65%
  |                                                                            
  |==============================================                        |  66%
  |                                                                            
  |===============================================                       |  66%
  |                                                                            
  |===============================================                       |  67%
  |                                                                            
  |===============================================                       |  68%
  |                                                                            
  |================================================                      |  68%
  |                                                                            
  |================================================                      |  69%
  |                                                                            
  |=================================================                     |  69%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |=================================================                     |  71%
  |                                                                            
  |==================================================                    |  71%
  |                                                                            
  |==================================================                    |  72%
  |                                                                            
  |===================================================                   |  72%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |====================================================                  |  74%
  |                                                                            
  |====================================================                  |  75%
  |                                                                            
  |=====================================================                 |  75%
  |                                                                            
  |=====================================================                 |  76%
  |                                                                            
  |======================================================                |  77%
  |                                                                            
  |======================================================                |  78%
  |                                                                            
  |=======================================================               |  78%
  |                                                                            
  |=======================================================               |  79%
  |                                                                            
  |========================================================              |  79%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |========================================================              |  81%
  |                                                                            
  |=========================================================             |  81%
  |                                                                            
  |=========================================================             |  82%
  |                                                                            
  |==========================================================            |  82%
  |                                                                            
  |==========================================================            |  83%
  |                                                                            
  |==========================================================            |  84%
  |                                                                            
  |===========================================================           |  84%
  |                                                                            
  |===========================================================           |  85%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |============================================================          |  86%
  |                                                                            
  |=============================================================         |  86%
  |                                                                            
  |=============================================================         |  87%
  |                                                                            
  |=============================================================         |  88%
  |                                                                            
  |==============================================================        |  88%
  |                                                                            
  |==============================================================        |  89%
  |                                                                            
  |===============================================================       |  89%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |===============================================================       |  91%
  |                                                                            
  |================================================================      |  91%
  |                                                                            
  |================================================================      |  92%
  |                                                                            
  |=================================================================     |  92%
  |                                                                            
  |=================================================================     |  93%
  |                                                                            
  |=================================================================     |  94%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |==================================================================    |  95%
  |                                                                            
  |===================================================================   |  95%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |====================================================================  |  96%
  |                                                                            
  |====================================================================  |  97%
  |                                                                            
  |====================================================================  |  98%
  |                                                                            
  |===================================================================== |  98%
  |                                                                            
  |===================================================================== |  99%
  |                                                                            
  |======================================================================|  99%
  |                                                                            
  |======================================================================| 100%</code></pre>
<div class="figure">
<span style="display:block;" id="fig:r1-base-map"></span>
<iframe src="maps/r1_map.html" width="100%" height="500px" data-external="1" style="border:none;">
</iframe>
<p class="caption">
FIGURE 10.1: Route 1 study area
</p>
</div>
<p>There are several different housing options along the corridor that serve a diverse population; these includes single-family homes, garden-style apartments, mobile homes, and senior communities. While not included as part of this analysis, it is also important to note that several motels along the corridor are serving as long-term housing options for some Chesterfield residents.</p>
<p>According to tract-level LEHD employment data from the Census Bureau’s <a href="https://onthemap.ces.census.gov/">OnTheMap</a> application, residents in this area largely work in the retail, health care and social assistance, construction, and accommodation and food services industries. “Administration and support and waste management and remediation services” is a broad category including office administration, security, cleaning, and other routine services for businesses and other organizations.</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:r1-industry">Table 10.1: </span>Top five most common industries for residents in the study area
</caption>
<thead><tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
Jobs
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Retail trade
</td>
<td style="text-align:right;">
958
</td>
</tr>
<tr>
<td style="text-align:left;">
Health care and social assistance
</td>
<td style="text-align:right;">
919
</td>
</tr>
<tr>
<td style="text-align:left;">
Construction
</td>
<td style="text-align:right;">
746
</td>
</tr>
<tr>
<td style="text-align:left;">
Accommodation and food services
</td>
<td style="text-align:right;">
710
</td>
</tr>
<tr>
<td style="text-align:left;">
Administration and support and waste management and remediation services
</td>
<td style="text-align:right;">
651
</td>
</tr>
</tbody>
</table></div>
<p><em>Source: U.S. Census Bureau. (2022). LEHD Origin-Destination Employment Statistics (2002-2019). Longitudinal-Employer Household Dynamics Program.</em></p>
<p>While specific wages for each industry and occupation are not available for the specific study area, the LEHD dataset does summarize monthly earnings for all workers into three pay bands. One in five workers earn less than $1,250 per month, which are likely part-time jobs. While many workers (42 percent) earn more than $3,333 monthly, or approximately $40,000 annually, the majority earn less. Most working residents in the study area are employed full-time at low-wage jobs, or are underemployed.</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:r1-earnings">Table 10.2: </span>Monthly earnings for residents in the study area
</caption>
<thead><tr>
<th style="text-align:left;">
Monthly earnings (dollars)
</th>
<th style="text-align:right;">
Percent
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
1,250 or less
</td>
<td style="text-align:right;">
20.2%
</td>
</tr>
<tr>
<td style="text-align:left;">
1,251 to 3,333
</td>
<td style="text-align:right;">
37.9%
</td>
</tr>
<tr>
<td style="text-align:left;">
More than 3,333
</td>
<td style="text-align:right;">
41.9%
</td>
</tr>
</tbody>
</table></div>
<p><em>Source: U.S. Census Bureau. (2022). LEHD Origin-Destination Employment Statistics (2002-2019). Longitudinal-Employer Household Dynamics Program.</em></p>
<p>The LEHD does not tabulate jobs by specific occupation, but based on the most common industries of workers in the study area, the table below shows the most likely common occupations (and regional wages) for these workers.</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:r1-jobs">Table 10.3: </span>Wages for common occupations in the study area
</caption>
<thead><tr>
<th style="text-align:left;">
Occupation
</th>
<th style="text-align:right;">
Mean hourly wage
</th>
<th style="text-align:right;">
Mean annual wage
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Construction laborers
</td>
<td style="text-align:right;">
$16.50
</td>
<td style="text-align:right;">
$34,310.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Retail salespersons
</td>
<td style="text-align:right;">
$13.85
</td>
<td style="text-align:right;">
$28,800.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Janitors and cleaners
</td>
<td style="text-align:right;">
$13.02
</td>
<td style="text-align:right;">
$27,450.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Home health and personal care aides
</td>
<td style="text-align:right;">
$11.51
</td>
<td style="text-align:right;">
$23,930.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Fast food and counter workers
</td>
<td style="text-align:right;">
$11.29
</td>
<td style="text-align:right;">
$23,490.00
</td>
</tr>
</tbody>
</table></div>
</div>
<div id="cost-burden" class="section level2" number="10.3">
<h2>
<span class="header-section-number">10.3</span> Cost burden<a class="anchor" aria-label="anchor" href="#cost-burden"><i class="fas fa-link"></i></a>
</h2>
<p>here is some text</p>
</div>
<div id="homeowner-affordability-1" class="section level2" number="10.4">
<h2>
<span class="header-section-number">10.4</span> Homeowner affordability<a class="anchor" aria-label="anchor" href="#homeowner-affordability-1"><i class="fas fa-link"></i></a>
</h2>
<p>Along the Route 1 corridor, there have been about 51 home sales each quarter between 2012 and 2021. Like the rest of the county, the pandemic has impacted home prices in one of the county’s most affordable areas. As of 2021, the median sale price was $251,000, a 109 percent increase from 2012 when the median home sale price was $120,250.</p>
<div class="figure">
<span style="display:block;" id="fig:r1-med-sales"></span>
<img src="part-1b-5_files/figure-html/r1-med-sales-1.png" alt="Median single-family home sales price in study area" width="100%" style="border:none;"><p class="caption">
FIGURE 10.2: Median single-family home sales price in study area
</p>
</div>
<p><em>Source: CVR MLS. 2022 includes all sales through April 13, 2022.</em></p>
<p>In order to afford a home at this price, a household would need to make <strong>$62,790</strong>. While this is /$16,391 (21 percent) less than the income needed to afford the median sales price for the whole county, this is significantly above what most workers in the study area earn. The table below shows the assumptions made to calculate this figure.</p>
<div class="inline-table"><table class="table table-condensed table-hover table-striped" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:r1-home-price">Table 10.4: </span>Calculated income needed to buy median-priced home in the study area
</caption>
<thead><tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:right;">
Value
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Median sales price
</td>
<td style="text-align:right;">
$251,000
</td>
</tr>
<tr>
<td style="text-align:left;">
Downpayment
</td>
<td style="text-align:right;">
5.0%
</td>
</tr>
<tr>
<td style="text-align:left;">
Closing costs
</td>
<td style="text-align:right;">
1.5%
</td>
</tr>
<tr>
<td style="text-align:left;">
Loan amount
</td>
<td style="text-align:right;">
$277,766
</td>
</tr>
<tr>
<td style="text-align:left;">
Interest rate
</td>
<td style="text-align:right;">
4.42%
</td>
</tr>
<tr>
<td style="text-align:left;">
Monthly utilities
</td>
<td style="text-align:right;">
$250
</td>
</tr>
<tr>
<td style="text-align:left;">
Monthly payment
</td>
<td style="text-align:right;">
$1,644.23
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Income needed to buy home
</td>
<td style="text-align:right;font-weight: bold;">
$62,790
</td>
</tr>
</tbody>
</table></div>
<p><em>Sources: CVR MLS and Freddie Mac Primary Mortgage Market Survey.</em></p>
<p>Census estimates also show that most renters across the study area live in households that have incomes well below what it would require to buy a home in their neighborhood. Most of the census tracts have median renter incomes between $20,000 and $50,000.</p>
<div class="figure">
<span style="display:block;" id="fig:r1-renter-income"></span>
<img src="part-1b-5_files/figure-html/r1-renter-income-1.png" alt="Median renter income by tract in the study area" width="100%" style="border:none;"><p class="caption">
FIGURE 10.3: Median renter income by tract in the study area
</p>
</div>
<p><em>Source: U.S. Census Bureau, American Community Survey, 5-year estimates, Table B25119.</em></p>
<p>For workers who live along the Route 1 corridor, these price increases are continuing to keep homeownership out of reach. Residents largely work in the retail, health care and social assistance, construction, and accommodation and food services industries. Based on the average annual wages in the Richmond region, very few workers in these industries could afford to own a home along the corridor. The few homes that are sold at these prices (below $160,000) are often in disrepair and, if sold, purchased by investors to rehabilitate and sell at a higher price.</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:r1-jobs-price">Table 10.5: </span>Maximum home sales price for common occupations in the study area
</caption>
<thead><tr>
<th style="text-align:left;">
Occupation
</th>
<th style="text-align:right;">
Maximum home sales price
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Construction laborers
</td>
<td style="text-align:right;">
$159,494
</td>
</tr>
<tr>
<td style="text-align:left;">
Retail salespersons
</td>
<td style="text-align:right;">
$133,880
</td>
</tr>
<tr>
<td style="text-align:left;">
Janitors and cleaners
</td>
<td style="text-align:right;">
$127,604
</td>
</tr>
<tr>
<td style="text-align:left;">
Home health and personal care aides
</td>
<td style="text-align:right;">
$111,241
</td>
</tr>
<tr>
<td style="text-align:left;">
Fast food and counter workers
</td>
<td style="text-align:right;">
$109,196
</td>
</tr>
</tbody>
</table></div>
<p><em>Sources: Freddie Mac Primary Mortgage Market Survey and Bureau of Labor Statistics, Occupational Employment and Wage Statistics, May 2021.</em></p>
</div>
<div id="renter-affordability-1" class="section level2" number="10.5">
<h2>
<span class="header-section-number">10.5</span> Renter affordability<a class="anchor" aria-label="anchor" href="#renter-affordability-1"><i class="fas fa-link"></i></a>
</h2>
<p>There are at least 2,076 existing rental units across 22 properties along the Route 1 corridor, with 204 additional units proposed. This does not include a significant amount of mobile home park units like Shady Hill, which contains at least 110 units alone. Thirty-seven percent of these units are located in a development with some rent restrictions that help ensure affordability.</p>
<p>Since 2010, rents along the corridor have been on the rise, from a low of $973 in 2011 to a 2022 year-to-date high of $1,085. The increasing average rent can be attributed to the entry of several higher-end rentals into the market, like Colony Village.</p>
<div class="figure">
<span style="display:block;" id="fig:r1-rents"></span>
<img src="part-1b-5_files/figure-html/r1-rents-1.png" alt="Median asking rent in the study area" width="100%" style="border:none;"><p class="caption">
FIGURE 10.4: Median asking rent in the study area
</p>
</div>
<p><em>Source: CoStar Group, Inc.</em></p>
<p>The rise in rental demand—and subsequently, prices—along the corridor is putting significant pressure on workers who live in the area. In order to afford the average rent of $1,083 in 2021, a single individual would need to make $43,320 a year, or $20.83 an hour.</p>
<p>Some of the most common jobs occupied by corridor residents pay an hourly wage that is nearly half that needed to afford the typical rent. Fast wood workers, home health aides, and childcare workers all have an average hourly wage less than $12.00. In order to afford a rental on a single income, they would need a monthly rent closer to $600—a rent that is becoming harder and harder to find even in older properties like the Bellwood Maisonettes that now list their one bedroom apartments at $1,000 a month.</p>
<div class="inline-table"><table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:r1-renter-affordability">Table 10.6: </span>Maximum monthly rent for common occupations in the study area
</caption>
<thead><tr>
<th style="text-align:left;">
Occupation
</th>
<th style="text-align:right;">
Maximum monthly rent
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Construction laborers
</td>
<td style="text-align:right;">
$857.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Retail salespersons
</td>
<td style="text-align:right;">
$720.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Janitors and cleaners
</td>
<td style="text-align:right;">
$686.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Home health and personal care aides
</td>
<td style="text-align:right;">
$598.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Fast food and counter workers
</td>
<td style="text-align:right;">
$587.25
</td>
</tr>
</tbody>
</table></div>
<p>With these rent increases, renters along the corridor face increasing challenges. They often need to work additional hours, count on additional income from a partner, roommate, or family member, or compromise quality for affordability.</p>
<p>The majority of these properties are considered NOAH given their age, condition, and rent. But few, if any of these properties, have experienced any major renovations in the past decades—meaning that they are at-risk of deteriorating conditions or redevelopment. In either case, this puts residents in a precarious position: continue to live in unhealthy and unsafe conditions or move (voluntarily or involuntarily).</p>
</div>
<div id="takeaways-9" class="section level2" number="10.6">
<h2>
<span class="header-section-number">10.6</span> Takeaways<a class="anchor" aria-label="anchor" href="#takeaways-9"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>Many workers in the northern Route 1 corridor are part of the county’s essential workforce. However, the jobs they hold command wages that are usually well below average.</li>
<li>Despite the lower home values in the study area, sales prices are rapidly increasing, putting homeownership out of reach for most residents of these neighborhoods.</li>
<li>Increasing rents will force current residents to absorb additional housing cost burden, or find cheaper options after making concessions about the location or quality of their home.</li>
</ul>
</div>
</div>




















  <div class="chapter-nav">
<div class="prev"><a href="part-1b-4.html"><span class="header-section-number">9</span> Ability-to-pay</a></div>
<div class="empty"></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#part-1b-5"><span class="header-section-number">10</span> Route 1 affordability analysis</a></li>
<li><a class="nav-link" href="#background-8"><span class="header-section-number">10.1</span> Background</a></li>
<li><a class="nav-link" href="#study-area"><span class="header-section-number">10.2</span> Study area</a></li>
<li><a class="nav-link" href="#cost-burden"><span class="header-section-number">10.3</span> Cost burden</a></li>
<li><a class="nav-link" href="#homeowner-affordability-1"><span class="header-section-number">10.4</span> Homeowner affordability</a></li>
<li><a class="nav-link" href="#renter-affordability-1"><span class="header-section-number">10.5</span> Renter affordability</a></li>
<li><a class="nav-link" href="#takeaways-9"><span class="header-section-number">10.6</span> Takeaways</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/hdadvisors/chesterfield-market-analysis/blob/master/part-1b-5.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/hdadvisors/chesterfield-market-analysis/edit/master/part-1b-5.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Chesterfield County Rental Market Analysis</strong>" was written by HDAdvisors. It was last built on 2022-04-20.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>
</body>
</html>
