<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chesterfield County Rental Market Analysis - 9&nbsp; Ability-to-pay</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./part-1b-5.html" rel="next">
<link href="./part-1b-3.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Ability-to-pay</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Chesterfield County Rental Market Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/hdadvisors/chesterfield-market-analysis/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="./Chesterfield-County-Rental-Market-Analysis.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">About</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">PART 1-A: LITERATURE REVIEW</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1a-1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Planning for housing in Chesterfield County</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1a-2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Measures of housing affordability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1a-3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Market-affordable housing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1a-4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Concentrations of affordable housing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1a-5.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Renter tenancy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">PART 1-B: DEMOGRAPHIC AND AFFORDABILITY ANALYSIS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1b-1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data sources and reliability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1b-2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Household income</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1b-3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Household cost burden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1b-4.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Ability-to-pay</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-1b-5.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Route 1 affordability analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">PART 2-A: COUNTYWIDE MARKET ANALYSIS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-2a-1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Rental market summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-2a-2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Rental spatial analyis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-2a-3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Market comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-2a-4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Outreach</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">PART 2-B: CORRIDOR CASE STUDIES</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-2b-1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Route 1 corridor analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./part-2b-2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Eastern Hull Street Road corridor analysis</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background"><span class="toc-section-number">9.1</span>  Background</a></li>
  <li><a href="#homeowner-affordability" id="toc-homeowner-affordability" class="nav-link" data-scroll-target="#homeowner-affordability"><span class="toc-section-number">9.2</span>  Homeowner affordability</a></li>
  <li><a href="#renter-affordability" id="toc-renter-affordability" class="nav-link" data-scroll-target="#renter-affordability"><span class="toc-section-number">9.3</span>  Renter affordability</a></li>
  <li><a href="#takeaways" id="toc-takeaways" class="nav-link" data-scroll-target="#takeaways"><span class="toc-section-number">9.4</span>  Takeaways</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="part-1b-4" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Ability-to-pay</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>This section compares common wages for workers across Chesterfield County to actual housing costs for both homeownership and renting. The analysis reflects the ability for Chesterfield workforce to pay for current housing costs.</p>
<div class="cell">

</div>
<section id="background" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="background"><span class="header-section-number">9.1</span> Background</h2>
<p>Affording a home in Chesterfield County—whether to own or rent— is directly tied to the incomes that households earn. There are diverse job opportunities across the region, and while some common jobs do pay well-above minimum wage, housing costs are rising faster.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-top-occupations" class="anchored">

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.1:  Top five most common occupations in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Jobs </th>
   <th style="text-align:right;"> Mean hourly wage </th>
   <th style="text-align:right;"> Mean annual wage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Retail salespersons </td>
   <td style="text-align:right;"> 18,770 </td>
   <td style="text-align:right;"> $13.85 </td>
   <td style="text-align:right;"> $28,800 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fast food and counter workers </td>
   <td style="text-align:right;"> 16,930 </td>
   <td style="text-align:right;"> $11.29 </td>
   <td style="text-align:right;"> $23,490 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Customer service representatives </td>
   <td style="text-align:right;"> 13,560 </td>
   <td style="text-align:right;"> $17.51 </td>
   <td style="text-align:right;"> $36,410 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Registered nurses </td>
   <td style="text-align:right;"> 12,910 </td>
   <td style="text-align:right;"> $36.99 </td>
   <td style="text-align:right;"> $76,940 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Home health and personal care aides </td>
   <td style="text-align:right;"> 9,390 </td>
   <td style="text-align:right;"> $11.51 </td>
   <td style="text-align:right;"> $23,930 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Sources: </span> <sup></sup> Bureau of Labor Statistics, Occupational Employment and Wage Statistics, May 2021.</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>A diverse workforce also requires diverse housing for those workers. When workers can’t find housing in a community, they either have to commute in or they search for work elsewhere. More in-commuters can exacerbate traffic congestion and increase the amount of spending on transportation costs, while the loss of workers can put strain on local economies.</p>
<p>Another important part of a diverse workforce are public sector jobs, like teachers and police officers. Affordable housing to these households can be the deciding factor for attracting an adequate and talented pool of public service workers that educate our children and keep our neighborhoods safe.</p>
<p>The table below shows the median annual wage for six common occupations with Chesterfield County government. These positions generally pay higher than the county’s most prevalent private-sector jobs.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-public-sector" class="anchored">

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.2:  Public sector occupations in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Median annual wage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Planners </td>
   <td style="text-align:right;"> $66,202 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Police officers </td>
   <td style="text-align:right;"> $59,470 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CCPS teachers </td>
   <td style="text-align:right;"> $54,937 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Firefighters </td>
   <td style="text-align:right;"> $53,428 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Emergency communications officers </td>
   <td style="text-align:right;"> $44,166 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Administrative workers </td>
   <td style="text-align:right;"> $44,115 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Source: </span> <sup></sup> Chesterfield County.</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>Understanding the ability of a range of job types to afford housing in a county contributes to economic development goals and helps ensure that workers that live in the county can continue to live in the county. When people both live and work in a community, they are able to spend less time on the road and more time with their families and investing in their neighborhoods.</p>
</section>
<section id="homeowner-affordability" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="homeowner-affordability"><span class="header-section-number">9.2</span> Homeowner affordability</h2>
<p>Homeownership is more difficult to achieve in Chesterfield County The COVID-19 pandemic further tightened the housing market across America, and the Richmond region was no exception. The low supply of homes-for-sale coupled with record low mortgage interest rates placed pressure on local housing markets, especially in the suburbs.</p>
<p>The median home sale price in Chesterfield County has increased by 39 percent since before the pandemic in 2019—from $269,000 to $371,480 in 2022 year-to-date.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cf-med-sales" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="part-1b-4_files/figure-html/fig-cf-med-sales-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;9.1: Median single-family home sales price in Chesterfield County</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In order to afford a home at this price, a household would need to make <strong>$89,889</strong> at the current average annual interest rate.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The table below shows the assumptions made to calculate this figure.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cf-home-price" class="anchored">

<table class="table table-condensed table-hover table-striped" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.3:  Calculated income needed to buy median-priced home in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:right;"> Value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Median sales price </td>
   <td style="text-align:right;"> $371,480 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Downpayment </td>
   <td style="text-align:right;"> 5.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Closing costs </td>
   <td style="text-align:right;"> 1.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Loan amount </td>
   <td style="text-align:right;"> $358,280 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Interest rate </td>
   <td style="text-align:right;"> 4.65% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Monthly utilities </td>
   <td style="text-align:right;"> $250 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Monthly payment </td>
   <td style="text-align:right;"> $2,097.42 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Income needed to buy home </td>
   <td style="text-align:right;font-weight: bold;"> $89,889 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Sources: </span> <sup></sup> CVR MLS and Freddie Mac Primary Mortgage Market Survey.</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>This minimum income is about $37,000 more than the 2020 median household income for renters in Chesterfield ($53,147). In fact, through 2020, the average renter household income is unable to support a home sales price above $250,000.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cf-renter-income-afford" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="part-1b-4_files/figure-html/fig-cf-renter-income-afford-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;9.2: Median household income and affordable home sales price for renters in Chesterfield County</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Compared to 2021 average wages, several common occupations in the county would also struggle to afford the typical home price in the county in 2021. For example, customer service representatives average hourly wage of $17.51 could only afford a monthly mortgage payment for a home priced below $170,000. Even with an hourly wage that is three times that of the Virginia minimum wage ($11.00 per hour), households in the county would still struggle to afford a home.</p>
<p>The table below shows the maximum home sales price affordable at the current average wages for the five most common occupations in Chesterfield County.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cf-jobs-price" class="anchored">

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.4:  Maximum home sales price for five most common occupations in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Jobs </th>
   <th style="text-align:right;"> Maximum home sales price </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Retail salespersons </td>
   <td style="text-align:right;"> 18,770 </td>
   <td style="text-align:right;"> $130,324 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fast food and counter workers </td>
   <td style="text-align:right;"> 16,930 </td>
   <td style="text-align:right;"> $106,296 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Customer service representatives </td>
   <td style="text-align:right;"> 13,560 </td>
   <td style="text-align:right;"> $164,761 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Registered nurses </td>
   <td style="text-align:right;"> 12,910 </td>
   <td style="text-align:right;"> $348,165 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Home health and personal care aides </td>
   <td style="text-align:right;"> 9,390 </td>
   <td style="text-align:right;"> $108,287 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Sources: </span> <sup></sup> Freddie Mac Primary Mortgage Market Survey and Bureau of Labor Statistics, Occupational Employment and Wage Statistics, May 2021.</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>Among public sector employees working for the county, maximum home sales prices are higher, reflecting the stronger wages they command. However, most of these prices are at or below $300,000, still well under the county’s current median sales price of $371,480.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cf-public-price" class="anchored">

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.5:  Maximum home sales price for public sector occupations in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Maximum home sales price </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Planners </td>
   <td style="text-align:right;"> $299,574 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Police officers </td>
   <td style="text-align:right;"> $269,111 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CCPS teachers </td>
   <td style="text-align:right;"> $248,598 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Firefighters </td>
   <td style="text-align:right;"> $241,770 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Emergency communications officers </td>
   <td style="text-align:right;"> $199,858 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Administrative workers </td>
   <td style="text-align:right;"> $199,627 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Sources: </span> <sup></sup> Freddie Mac Primary Mortgage Market Survey and Chesterfield County.</td></tr></tfoot>
</table>

</div>
</div>
</div>
</section>
<section id="renter-affordability" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="renter-affordability"><span class="header-section-number">9.3</span> Renter affordability</h2>
<p>The housing supply shortage is also being felt in the rental housing market. Small landlords exiting the rental market and low supply are exacerbating the challenges renters were facing even before the pandemic. For many renters in low paying jobs, the pandemic impacts were heightened for those that could not work-from-home and depended on shuttered service industry jobs. Slow wage growth and increasing rental prices combined to put pressure on the housing stability of essential workers.</p>
<p>Post-recession average asking rent in the county hit a low of $1,207 in 2012 (adjusted to current dollars), but has been on the rise ever since. From 2012 to 2019, average rents rose an average of 0.5 percent each year until 2020, the year of the pandemic.</p>
<p>Between 2019 and 2020, average rent in the county rose by 4 percent ($61)—from $1,366 to $1,427, a substantial increase for individuals and families on tight budgets. Today, the average rent in the county is around $1,500.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cf-rents" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="part-1b-4_files/figure-html/fig-cf-rents-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;9.3: Average asking rent in Chesterfield County: 2000 Q1 to 2022 Q2</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Current minimum annual incomes needed to afford the average apartment in the county—without becoming cost-burdened—start around $52,000 for a 1 bedroom unit. Two bedroom apartments rent at right about the overall average, requiring at least $59,560. Three bedrooms units command a much higher premium over $1,700 per month. Renters looking for these larger units will need an income of $68,320 or more to budget comfortably.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cf-rents-br" class="anchored">

<table class="table table-condensed table-hover table-striped" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.6:  Calculated income needed to afford average rents by bedroom in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Bedrooms </th>
   <th style="text-align:right;"> Average rent </th>
   <th style="text-align:right;"> Income needed </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 bedroom </td>
   <td style="text-align:right;"> $1,301 </td>
   <td style="text-align:right;"> $52,040 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 bedrooms </td>
   <td style="text-align:right;"> $1,489 </td>
   <td style="text-align:right;"> $59,560 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 bedrooms </td>
   <td style="text-align:right;"> $1,708 </td>
   <td style="text-align:right;"> $68,320 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> All apartments </td>
   <td style="text-align:right;font-weight: bold;"> $1,499 </td>
   <td style="text-align:right;font-weight: bold;"> $59,960 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Source: </span> <sup></sup> CoStar Group, Inc.</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>This rent is increasingly unaffordable to some of the most common occupations in the county, like retail salespersons and home health aides. For a retail salesperson with an average hourly wage of $13.85, a rent on a single income would be more affordable at $672 to $748 cheaper than the typical rent in the county.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cf-renter-affordability" class="anchored">

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.7:  Maximum monthly rent for five most common occupations in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Jobs </th>
   <th style="text-align:right;"> Maximum monthly rent </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Retail salespersons </td>
   <td style="text-align:right;"> 18,770 </td>
   <td style="text-align:right;"> $720.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fast food and counter workers </td>
   <td style="text-align:right;"> 16,930 </td>
   <td style="text-align:right;"> $587.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Customer service representatives </td>
   <td style="text-align:right;"> 13,560 </td>
   <td style="text-align:right;"> $910.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Registered nurses </td>
   <td style="text-align:right;"> 12,910 </td>
   <td style="text-align:right;"> $1,923.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Home health and personal care aides </td>
   <td style="text-align:right;"> 9,390 </td>
   <td style="text-align:right;"> $598.25 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Sources: </span> <sup></sup> CoStar Group, Inc. and Bureau of Labor Statistics, Occupational Employment and Wage Statistics, May 2021.</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>CCPS teachers with a median salary of $54,937 would also be hard pressed to afford the typical rent, especially for units with two or more bedrooms. For an essential part of the workforce there would need to be rental units priced lower at $1,373. Other public sector workers like firefighters, emergency communication officers, and government administrative workers would find it increasingly difficult to find affordable rental housing in the county’s high demand areas.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-cf-renter-public-affordability" class="anchored">

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;border-bottom: 0;"><caption>Table&nbsp;9.8:  Maximum monthly rent for public sector occupations in Chesterfield County </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Maximum monthly rent </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Planners </td>
   <td style="text-align:right;"> $1,655.05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Police officers </td>
   <td style="text-align:right;"> $1,486.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CCPS teachers </td>
   <td style="text-align:right;"> $1,373.42 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Firefighters </td>
   <td style="text-align:right;"> $1,335.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Emergency communications officers </td>
   <td style="text-align:right;"> $1,104.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Administrative workers </td>
   <td style="text-align:right;"> $1,102.88 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Sources: </span> <sup></sup> CoStar Group, Inc. and Chesterfield County.</td></tr></tfoot>
</table>

</div>
</div>
</div>
</section>
<section id="takeaways" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="takeaways"><span class="header-section-number">9.4</span> Takeaways</h2>
<ul>
<li>Although Chesterfield has a relatively high median household income in the region, many of the county’s essential workers are not earning enough to keep up with the housing market.</li>
<li>Homeownership will be increasingly out-of-reach for many workers if current supply and demand trends continue, and especially if interest rates begin rising.</li>
<li>The average monthly rent in Chesterfield is now around $1,500. This is very unaffordable to most of the county’s retail, service, and healthcare service workers.</li>
</ul>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>As of August 31, 2022.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Freddie Mac 30-Year Fixed Rate Mortgage Annual Average as of August 31, 2022.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Data current through 2022 Q2.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./part-1b-3.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Household cost burden</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./part-1b-5.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Route 1 affordability analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>