# Ability-to-pay {#part-1b-4}

This section compares common wages for workers across Chesterfield County to actual housing costs for both homeownership and renting. The analysis reflects the ability for Chesterfield workforce to pay for current housing costs.



## Background

Affording a home in Chesterfield County—whether to own or rent— is directly tied to the incomes that households earn. There are diverse job opportunities across the region, and while some common jobs do pay well-above minimum wage, housing costs are rising faster.

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>(\#tab:top-occupations)Top five most common occupations in Chesterfield County</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Jobs </th>
   <th style="text-align:right;"> Mean hourly wage </th>
   <th style="text-align:right;"> Mean annual wage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Retail salespersons </td>
   <td style="text-align:right;"> 18,770 </td>
   <td style="text-align:right;"> $13.85 </td>
   <td style="text-align:right;"> $28,800 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fast food and counter workers </td>
   <td style="text-align:right;"> 16,930 </td>
   <td style="text-align:right;"> $11.29 </td>
   <td style="text-align:right;"> $23,490 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Customer service representatives </td>
   <td style="text-align:right;"> 13,560 </td>
   <td style="text-align:right;"> $17.51 </td>
   <td style="text-align:right;"> $36,410 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Registered nurses </td>
   <td style="text-align:right;"> 12,910 </td>
   <td style="text-align:right;"> $36.99 </td>
   <td style="text-align:right;"> $76,940 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Home health and personal care aides </td>
   <td style="text-align:right;"> 9,390 </td>
   <td style="text-align:right;"> $11.51 </td>
   <td style="text-align:right;"> $23,930 </td>
  </tr>
</tbody>
</table>

*Source: Bureau of Labor Statistics, Occupational Employment and Wage Statistics, May 2021.*

A diverse workforce also requires diverse housing for those workers. When workers can’t find housing in a community, they either have to commute in or they search for work elsewhere. More in-commuters can exacerbate traffic congestion and increase the amount of spending on transportation costs, while the loss of workers can put strain on local economies.

Another important part of a diverse workforce are public sector jobs, like teachers and police officers. Affordable housing to these households can be the deciding factor for attracting an adequate and talented pool of public service workers that educate our children and keep our neighborhoods safe.

The table below shows the median annual wage for six common occupations with Chesterfield County government. These positions generally pay higher than the county's most prevelant private-sector jobs.

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>(\#tab:public-sector)Public sector occupations in Chesterfield County</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Median annual wage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Planners </td>
   <td style="text-align:right;"> $66,202 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Police officers </td>
   <td style="text-align:right;"> $59,470 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CCPS teachers </td>
   <td style="text-align:right;"> $54,937 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Firefighters </td>
   <td style="text-align:right;"> $53,428 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Emergency communications officers </td>
   <td style="text-align:right;"> $44,166 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Administrative workers </td>
   <td style="text-align:right;"> $44,115 </td>
  </tr>
</tbody>
</table>

*Source: Chesterfield County.*

Understanding the ability of a range of job types to afford housing in a county contributes to economic development goals and helps ensure that workers that live in the county can continue to live in the county. When people both live and work in a community, they are able to spend less time on the road and more time with their families and investing in their neighborhoods.

## Homeowner affordability

Homeownership is more difficult to achieve in Chesterfield County The COVID-19 pandemic further tightened the housing market across America, and the Richmond region was no exception. The low supply of homes-for-sale coupled with record low mortgage interest rates placed pressure on local housing markets, especially in the suburbs.

The median home sale price in Chesterfield County has increased by 23 percent since before the pandemic in 2019---from $269,000 to $330,000 in 2021.

<div class="figure">
<img src="part-1b-4_files/figure-html/cf-med-sales-1.png" alt="Median single-family home sales price in Chesterfield County" width="100%" style="border:none;" />
<p class="caption">(\#fig:cf-med-sales)Median single-family home sales price in Chesterfield County</p>
</div>

*Source: CVR MLS. 2022 includes all sales through March.*

In order to afford a home at this price, a household would need to make **\$79,181**. The table below shows the assumptions made to calculate this figure.

<table class="table table-condensed table-hover table-striped" style="margin-left: auto; margin-right: auto;">
<caption>(\#tab:cf-home-price)Calculated income needed to buy median-priced home in Chesterfield County</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:right;"> Value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Median sales price </td>
   <td style="text-align:right;"> $330,000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Downpayment </td>
   <td style="text-align:right;"> 5.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Closing costs </td>
   <td style="text-align:right;"> 1.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Loan amount </td>
   <td style="text-align:right;"> $318,274 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Interest rate </td>
   <td style="text-align:right;"> 4.42% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Monthly utilities </td>
   <td style="text-align:right;"> $250 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Monthly payment </td>
   <td style="text-align:right;"> $1,847.55 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Income needed to buy home </td>
   <td style="text-align:right;font-weight: bold;"> $79,181 </td>
  </tr>
</tbody>
</table>

*Sources: CVR MLS and Freddie Mac Primary Mortgage Market Survey.*

This minimum income is about \$25,000 more than the 2020 median household income for renters in Chesterfield. In fact, through 2020, the average renter household income is unable to support a home sales price above $250,000.



<div class="figure">
<img src="part-1b-4_files/figure-html/cf-renter-income-afford-1.png" alt="Median household income and affordable home sales price for renters in Chesterfield County" width="100%" style="border:none;" />
<p class="caption">(\#fig:cf-renter-income-afford)Median household income and affordable home sales price for renters in Chesterfield County</p>
</div>

*Sources: U.S. Census Bureau, American Community Survey, 5-year estimates, Table B25119 and Freddie Mac Primary Mortgage Market Survey.*

Compared to 2021 average wages, several common occupations in the county would also struggle to afford the typical home price in the county in 2021. For example, customer service representatives average hourly wage of \$17.51 could only afford a monthly mortgage payment for a home priced below \$170,000. Even with an hourly wage that is three times that of the Virginia minimum wage (\$11.00 per hour), households in the county would still struggle to afford a home.

The table below shows the maximum home sales price affordable at the current average wages for the five most common occupations in Chesterfield County.

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>(\#tab:cf-jobs-price)Maximum home sales price for five most common occupations in Chesterfield County</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Jobs </th>
   <th style="text-align:right;"> Maximum home sales price </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Retail salespersons </td>
   <td style="text-align:right;"> 18,770 </td>
   <td style="text-align:right;"> $133,880 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fast food and counter workers </td>
   <td style="text-align:right;"> 16,930 </td>
   <td style="text-align:right;"> $109,196 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Customer service representatives </td>
   <td style="text-align:right;"> 13,560 </td>
   <td style="text-align:right;"> $169,256 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Registered nurses </td>
   <td style="text-align:right;"> 12,910 </td>
   <td style="text-align:right;"> $357,663 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Home health and personal care aides </td>
   <td style="text-align:right;"> 9,390 </td>
   <td style="text-align:right;"> $111,241 </td>
  </tr>
</tbody>
</table>

*Sources: Freddie Mac Primary Mortgage Market Survey and Bureau of Labor Statistics, Occupational Employment and Wage Statistics, May 2021.*

Among public sector employees working for the county, maximum home sales prices are higher, reflecting the stronger wages they command. However, most of these prices are at or below \$300,000, still well under the county's current median sales price of $330,000.

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>(\#tab:cf-public-price)Maximum home sales price for public sector occupations in Chesterfield County</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Maximum home sales price </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Planners </td>
   <td style="text-align:right;"> $307,747 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Police officers </td>
   <td style="text-align:right;"> $276,452 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CCPS teachers </td>
   <td style="text-align:right;"> $255,380 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Firefighters </td>
   <td style="text-align:right;"> $248,366 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Emergency communications officers </td>
   <td style="text-align:right;"> $205,310 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Administrative workers </td>
   <td style="text-align:right;"> $205,073 </td>
  </tr>
</tbody>
</table>

*Sources: Freddie Mac Primary Mortgage Market Survey and Chesterfield County.*

## Renter affordability

The housing supply shortage is also being felt in the rental housing market. Small landlords exiting the rental market and low supply are exacerbating the challenges renters were facing even before the pandemic.  For many renters in low paying jobs, the pandemic impacts were heightened for those that could not work-from-home and depended on shuttered service industry jobs. Slow wage growth and increasing rental prices combined to put pressure on the housing stability of essential workers.

Post-recession average asking rent in the county hit a low of \$1,150 in 2012 (adjusted to current dollars), but has been on the rise ever since. From 2012 to 2019, average rents rose an average of 2 percent each year until 2020, the year of the pandemic. Between 2019 and 2020, average rent in the county rose by 5 percent (\$69)---from \$1,290 to \$1,359, a substantial increase for individuals and families on tight budgets. In 2021, average rent continued to rise to over \$1,400. 

<div class="figure">

```{=html}
<div id="htmlwidget-84dc79630c82774a8aaf" style="width:100%;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-84dc79630c82774a8aaf">{"x":{"data":[{"x":[11047,11138,11230,11322,11412,11503,11595,11687,11777,11868,11960,12052,12142,12233,12325,12417,12508,12599,12691,12783,12873,12964,13056,13148,13238,13329,13421,13513,13603,13694,13786,13878,13969,14060,14152,14244,14334,14425,14517,14609,14699,14790,14882,14974,15064,15155,15247,15339,15430,15521,15613,15705,15795,15886,15978,16070,16160,16251,16343,16435,16525,16616,16708,16800,16891,16982,17074,17166,17256,17347,17439,17531,17621,17712,17804,17896,17986,18077,18169,18261,18352,18443,18535,18627,18717,18808,18900,18992,19082],"y":[789,796,802,807,814,833,851,873,881,876,863,869,868,865,858,849,848,860,866,861,860,869,875,877,886,901,910,914,920,930,933,932,934,939,938,930,923,929,930,924,924,929,929,911,905,905,907,913,916,920,922,925,932,941,948,954,958,965,970,972,989,999,1005,1008,1023,1023,1023,1031,1048,1051,1068,1066,1090,1107,1110,1106,1132,1142,1146,1143,1157,1188,1213,1228,1272,1335,1363,1356,1387],"text":["period: 2000-03-31<br />value:  789<br />type: Asking rent<br />type: Asking rent","period: 2000-06-30<br />value:  796<br />type: Asking rent<br />type: Asking rent","period: 2000-09-30<br />value:  802<br />type: Asking rent<br />type: Asking rent","period: 2000-12-31<br />value:  807<br />type: Asking rent<br />type: Asking rent","period: 2001-03-31<br />value:  814<br />type: Asking rent<br />type: Asking rent","period: 2001-06-30<br />value:  833<br />type: Asking rent<br />type: Asking rent","period: 2001-09-30<br />value:  851<br />type: Asking rent<br />type: Asking rent","period: 2001-12-31<br />value:  873<br />type: Asking rent<br />type: Asking rent","period: 2002-03-31<br />value:  881<br />type: Asking rent<br />type: Asking rent","period: 2002-06-30<br />value:  876<br />type: Asking rent<br />type: Asking rent","period: 2002-09-30<br />value:  863<br />type: Asking rent<br />type: Asking rent","period: 2002-12-31<br />value:  869<br />type: Asking rent<br />type: Asking rent","period: 2003-03-31<br />value:  868<br />type: Asking rent<br />type: Asking rent","period: 2003-06-30<br />value:  865<br />type: Asking rent<br />type: Asking rent","period: 2003-09-30<br />value:  858<br />type: Asking rent<br />type: Asking rent","period: 2003-12-31<br />value:  849<br />type: Asking rent<br />type: Asking rent","period: 2004-03-31<br />value:  848<br />type: Asking rent<br />type: Asking rent","period: 2004-06-30<br />value:  860<br />type: Asking rent<br />type: Asking rent","period: 2004-09-30<br />value:  866<br />type: Asking rent<br />type: Asking rent","period: 2004-12-31<br />value:  861<br />type: Asking rent<br />type: Asking rent","period: 2005-03-31<br />value:  860<br />type: Asking rent<br />type: Asking rent","period: 2005-06-30<br />value:  869<br />type: Asking rent<br />type: Asking rent","period: 2005-09-30<br />value:  875<br />type: Asking rent<br />type: Asking rent","period: 2005-12-31<br />value:  877<br />type: Asking rent<br />type: Asking rent","period: 2006-03-31<br />value:  886<br />type: Asking rent<br />type: Asking rent","period: 2006-06-30<br />value:  901<br />type: Asking rent<br />type: Asking rent","period: 2006-09-30<br />value:  910<br />type: Asking rent<br />type: Asking rent","period: 2006-12-31<br />value:  914<br />type: Asking rent<br />type: Asking rent","period: 2007-03-31<br />value:  920<br />type: Asking rent<br />type: Asking rent","period: 2007-06-30<br />value:  930<br />type: Asking rent<br />type: Asking rent","period: 2007-09-30<br />value:  933<br />type: Asking rent<br />type: Asking rent","period: 2007-12-31<br />value:  932<br />type: Asking rent<br />type: Asking rent","period: 2008-03-31<br />value:  934<br />type: Asking rent<br />type: Asking rent","period: 2008-06-30<br />value:  939<br />type: Asking rent<br />type: Asking rent","period: 2008-09-30<br />value:  938<br />type: Asking rent<br />type: Asking rent","period: 2008-12-31<br />value:  930<br />type: Asking rent<br />type: Asking rent","period: 2009-03-31<br />value:  923<br />type: Asking rent<br />type: Asking rent","period: 2009-06-30<br />value:  929<br />type: Asking rent<br />type: Asking rent","period: 2009-09-30<br />value:  930<br />type: Asking rent<br />type: Asking rent","period: 2009-12-31<br />value:  924<br />type: Asking rent<br />type: Asking rent","period: 2010-03-31<br />value:  924<br />type: Asking rent<br />type: Asking rent","period: 2010-06-30<br />value:  929<br />type: Asking rent<br />type: Asking rent","period: 2010-09-30<br />value:  929<br />type: Asking rent<br />type: Asking rent","period: 2010-12-31<br />value:  911<br />type: Asking rent<br />type: Asking rent","period: 2011-03-31<br />value:  905<br />type: Asking rent<br />type: Asking rent","period: 2011-06-30<br />value:  905<br />type: Asking rent<br />type: Asking rent","period: 2011-09-30<br />value:  907<br />type: Asking rent<br />type: Asking rent","period: 2011-12-31<br />value:  913<br />type: Asking rent<br />type: Asking rent","period: 2012-03-31<br />value:  916<br />type: Asking rent<br />type: Asking rent","period: 2012-06-30<br />value:  920<br />type: Asking rent<br />type: Asking rent","period: 2012-09-30<br />value:  922<br />type: Asking rent<br />type: Asking rent","period: 2012-12-31<br />value:  925<br />type: Asking rent<br />type: Asking rent","period: 2013-03-31<br />value:  932<br />type: Asking rent<br />type: Asking rent","period: 2013-06-30<br />value:  941<br />type: Asking rent<br />type: Asking rent","period: 2013-09-30<br />value:  948<br />type: Asking rent<br />type: Asking rent","period: 2013-12-31<br />value:  954<br />type: Asking rent<br />type: Asking rent","period: 2014-03-31<br />value:  958<br />type: Asking rent<br />type: Asking rent","period: 2014-06-30<br />value:  965<br />type: Asking rent<br />type: Asking rent","period: 2014-09-30<br />value:  970<br />type: Asking rent<br />type: Asking rent","period: 2014-12-31<br />value:  972<br />type: Asking rent<br />type: Asking rent","period: 2015-03-31<br />value:  989<br />type: Asking rent<br />type: Asking rent","period: 2015-06-30<br />value:  999<br />type: Asking rent<br />type: Asking rent","period: 2015-09-30<br />value: 1005<br />type: Asking rent<br />type: Asking rent","period: 2015-12-31<br />value: 1008<br />type: Asking rent<br />type: Asking rent","period: 2016-03-31<br />value: 1023<br />type: Asking rent<br />type: Asking rent","period: 2016-06-30<br />value: 1023<br />type: Asking rent<br />type: Asking rent","period: 2016-09-30<br />value: 1023<br />type: Asking rent<br />type: Asking rent","period: 2016-12-31<br />value: 1031<br />type: Asking rent<br />type: Asking rent","period: 2017-03-31<br />value: 1048<br />type: Asking rent<br />type: Asking rent","period: 2017-06-30<br />value: 1051<br />type: Asking rent<br />type: Asking rent","period: 2017-09-30<br />value: 1068<br />type: Asking rent<br />type: Asking rent","period: 2017-12-31<br />value: 1066<br />type: Asking rent<br />type: Asking rent","period: 2018-03-31<br />value: 1090<br />type: Asking rent<br />type: Asking rent","period: 2018-06-30<br />value: 1107<br />type: Asking rent<br />type: Asking rent","period: 2018-09-30<br />value: 1110<br />type: Asking rent<br />type: Asking rent","period: 2018-12-31<br />value: 1106<br />type: Asking rent<br />type: Asking rent","period: 2019-03-31<br />value: 1132<br />type: Asking rent<br />type: Asking rent","period: 2019-06-30<br />value: 1142<br />type: Asking rent<br />type: Asking rent","period: 2019-09-30<br />value: 1146<br />type: Asking rent<br />type: Asking rent","period: 2019-12-31<br />value: 1143<br />type: Asking rent<br />type: Asking rent","period: 2020-03-31<br />value: 1157<br />type: Asking rent<br />type: Asking rent","period: 2020-06-30<br />value: 1188<br />type: Asking rent<br />type: Asking rent","period: 2020-09-30<br />value: 1213<br />type: Asking rent<br />type: Asking rent","period: 2020-12-31<br />value: 1228<br />type: Asking rent<br />type: Asking rent","period: 2021-03-31<br />value: 1272<br />type: Asking rent<br />type: Asking rent","period: 2021-06-30<br />value: 1335<br />type: Asking rent<br />type: Asking rent","period: 2021-09-30<br />value: 1363<br />type: Asking rent<br />type: Asking rent","period: 2021-12-31<br />value: 1356<br />type: Asking rent<br />type: Asking rent","period: 2022-03-31<br />value: 1387<br />type: Asking rent<br />type: Asking rent"],"type":"scatter","mode":"lines+markers","line":{"width":2.83464566929134,"color":"rgba(23,190,207,1)","dash":"solid"},"hoveron":"points","name":"Asking rent","legendgroup":"Asking rent","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(23,190,207,1)","opacity":0,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(23,190,207,1)"}},"frame":null,"hoverlabel":{"align":"left"}},{"x":[11047,11138,11230,11322,11412,11503,11595,11687,11777,11868,11960,12052,12142,12233,12325,12417,12508,12599,12691,12783,12873,12964,13056,13148,13238,13329,13421,13513,13603,13694,13786,13878,13969,14060,14152,14244,14334,14425,14517,14609,14699,14790,14882,14974,15064,15155,15247,15339,15430,15521,15613,15705,15795,15886,15978,16070,16160,16251,16343,16435,16525,16616,16708,16800,16891,16982,17074,17166,17256,17347,17439,17531,17621,17712,17804,17896,17986,18077,18169,18261,18352,18443,18535,18627,18717,18808,18900,18992,19082],"y":[1304,1305,1303,1301,1300,1322,1346,1382,1390,1371,1345,1345,1330,1328,1307,1289,1276,1284,1284,1264,1257,1261,1251,1241,1248,1258,1259,1269,1265,1265,1261,1244,1234,1224,1204,1222,1222,1223,1213,1196,1194,1202,1197,1165,1145,1133,1127,1129,1127,1129,1127,1124,1128,1139,1141,1145,1143,1145,1148,1153,1181,1184,1188,1191,1210,1200,1195,1196,1208,1210,1224,1212,1229,1240,1238,1230,1256,1256,1257,1246,1258,1302,1314,1322,1357,1395,1402,1372,1395],"text":["period: 2000-03-31<br />value: 1304<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2000-06-30<br />value: 1305<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2000-09-30<br />value: 1303<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2000-12-31<br />value: 1301<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2001-03-31<br />value: 1300<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2001-06-30<br />value: 1322<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2001-09-30<br />value: 1346<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2001-12-31<br />value: 1382<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2002-03-31<br />value: 1390<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2002-06-30<br />value: 1371<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2002-09-30<br />value: 1345<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2002-12-31<br />value: 1345<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2003-03-31<br />value: 1330<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2003-06-30<br />value: 1328<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2003-09-30<br />value: 1307<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2003-12-31<br />value: 1289<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2004-03-31<br />value: 1276<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2004-06-30<br />value: 1284<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2004-09-30<br />value: 1284<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2004-12-31<br />value: 1264<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2005-03-31<br />value: 1257<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2005-06-30<br />value: 1261<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2005-09-30<br />value: 1251<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2005-12-31<br />value: 1241<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2006-03-31<br />value: 1248<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2006-06-30<br />value: 1258<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2006-09-30<br />value: 1259<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2006-12-31<br />value: 1269<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2007-03-31<br />value: 1265<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2007-06-30<br />value: 1265<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2007-09-30<br />value: 1261<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2007-12-31<br />value: 1244<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2008-03-31<br />value: 1234<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2008-06-30<br />value: 1224<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2008-09-30<br />value: 1204<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2008-12-31<br />value: 1222<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2009-03-31<br />value: 1222<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2009-06-30<br />value: 1223<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2009-09-30<br />value: 1213<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2009-12-31<br />value: 1196<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2010-03-31<br />value: 1194<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2010-06-30<br />value: 1202<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2010-09-30<br />value: 1197<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2010-12-31<br />value: 1165<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2011-03-31<br />value: 1145<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2011-06-30<br />value: 1133<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2011-09-30<br />value: 1127<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2011-12-31<br />value: 1129<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2012-03-31<br />value: 1127<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2012-06-30<br />value: 1129<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2012-09-30<br />value: 1127<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2012-12-31<br />value: 1124<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2013-03-31<br />value: 1128<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2013-06-30<br />value: 1139<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2013-09-30<br />value: 1141<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2013-12-31<br />value: 1145<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2014-03-31<br />value: 1143<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2014-06-30<br />value: 1145<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2014-09-30<br />value: 1148<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2014-12-31<br />value: 1153<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2015-03-31<br />value: 1181<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2015-06-30<br />value: 1184<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2015-09-30<br />value: 1188<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2015-12-31<br />value: 1191<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2016-03-31<br />value: 1210<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2016-06-30<br />value: 1200<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2016-09-30<br />value: 1195<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2016-12-31<br />value: 1196<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2017-03-31<br />value: 1208<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2017-06-30<br />value: 1210<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2017-09-30<br />value: 1224<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2017-12-31<br />value: 1212<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2018-03-31<br />value: 1229<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2018-06-30<br />value: 1240<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2018-09-30<br />value: 1238<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2018-12-31<br />value: 1230<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2019-03-31<br />value: 1256<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2019-06-30<br />value: 1256<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2019-09-30<br />value: 1257<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2019-12-31<br />value: 1246<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2020-03-31<br />value: 1258<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2020-06-30<br />value: 1302<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2020-09-30<br />value: 1314<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2020-12-31<br />value: 1322<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2021-03-31<br />value: 1357<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2021-06-30<br />value: 1395<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2021-09-30<br />value: 1402<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2021-12-31<br />value: 1372<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)","period: 2022-03-31<br />value: 1395<br />type: Asking rent (inflation-adjusted)<br />type: Asking rent (inflation-adjusted)"],"type":"scatter","mode":"lines+markers","line":{"width":2.83464566929134,"color":"rgba(188,189,34,1)","dash":"solid"},"hoveron":"points","name":"Asking rent (inflation-adjusted)","legendgroup":"Asking rent (inflation-adjusted)","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(188,189,34,1)","opacity":0,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(188,189,34,1)"}},"frame":null,"hoverlabel":{"align":"left"}}],"layout":{"margin":{"t":39.9103362391034,"r":26.5670402656704,"b":26.2349522623495,"l":70.0705687007057},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(50,50,50,1)","family":"","size":13.2835201328352},"title":{"text":"<b> Average asking rent in Chesterfield County <\/b>","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[10638.9,19617.1],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[10957,12784,14610,16436,18262],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"outside","tickcolor":"rgba(50,50,50,1)","ticklen":3.65296803652968,"tickwidth":0.398505603985056,"showticklabels":true,"tickfont":{"color":"rgba(50,50,50,1)","family":"","size":13.2835201328352},"tickangle":-0,"showline":true,"linecolor":"rgba(50,50,50,1)","linewidth":0.398505603985056,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"y","title":{"text":"","font":{"color":"rgba(50,50,50,1)","family":"","size":13.2835201328352}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0,1500],"tickmode":"array","ticktext":["$0","$500","$1,000","$1,500"],"tickvals":[0,500,1000,1500],"categoryorder":"array","categoryarray":["$0","$500","$1,000","$1,500"],"nticks":null,"ticks":"outside","tickcolor":"rgba(50,50,50,1)","ticklen":3.65296803652968,"tickwidth":0.398505603985056,"showticklabels":true,"tickfont":{"color":"rgba(50,50,50,1)","family":"","size":13.2835201328352},"tickangle":-0,"showline":true,"linecolor":"rgba(50,50,50,1)","linewidth":0.398505603985056,"showgrid":true,"gridcolor":"rgba(211,211,211,1)","gridwidth":0.265670402656704,"zeroline":false,"anchor":"x","title":{"text":"Average asking rent","font":{"color":"rgba(50,50,50,1)","family":"","size":13.2835201328352}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"rgba(255,255,255,1)","borderwidth":1.88976377952756,"font":{"color":"rgba(50,50,50,1)","family":"","size":13.2835201328352},"title":{"text":"Type","font":{"color":null,"family":null,"size":0}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"modeBarButtonsToRemove":["zoom2d","pan2d","zoomIn2d","zoomOut2d","autoScale2d","resetScale2d","hoverClosestCartesian","hoverCompareCartesian","sendDataToCloud","toggleHover","resetViews","toggleSpikelines","resetViewMapbox","toggleSpikelines","resetViewMapbox","lasso2d","select2d"],"displaylogo":false},"source":"A","attrs":{"52341a216f34":{"x":{},"y":{},"colour":{},"type":"scatter"},"523435ba7ebc":{"x":{},"y":{},"colour":{}}},"cur_data":"52341a216f34","visdat":{"52341a216f34":["function (y) ","x"],"523435ba7ebc":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
```

<p class="caption">(\#fig:cf-rents)Average asking rent in Chesterfield County</p>
</div>

*Source: CoStar Group, Inc.*

This rent is increasingly unaffordable to some of the most common occupations in the county, like retail salespersons and home health aides. For a retail salesperson with an average hourly wage of \$13.85, a rent on a single income would be more affordable at \$672 to \$748 cheaper than the typical rent in the county. 

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>(\#tab:cf-renter-affordability)Maximum monthly rent for five most common occupations in Chesterfield County</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Jobs </th>
   <th style="text-align:right;"> Maximum monthly rent </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Retail salespersons </td>
   <td style="text-align:right;"> 18,770 </td>
   <td style="text-align:right;"> $720.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fast food and counter workers </td>
   <td style="text-align:right;"> 16,930 </td>
   <td style="text-align:right;"> $587.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Customer service representatives </td>
   <td style="text-align:right;"> 13,560 </td>
   <td style="text-align:right;"> $910.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Registered nurses </td>
   <td style="text-align:right;"> 12,910 </td>
   <td style="text-align:right;"> $1,923.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Home health and personal care aides </td>
   <td style="text-align:right;"> 9,390 </td>
   <td style="text-align:right;"> $598.25 </td>
  </tr>
</tbody>
</table>

*Source: CoStar Group, Inc. and Bureau of Labor Statistics, Occupational Employment and Wage Statistics, May 2021.*

CCPS teachers with a median salary of \$54,937 would also be hard pressed to afford the typical rent. For an essential part of the workforce there would need to be rental units priced lower at \$1,373. Other public sector workers like firefighters, emergency communication officers, and government administrative workers would find it increasingly difficult to find affordable rental housing in the county's high demand areas.

<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>(\#tab:cf-renter-public-affordability)Maximum monthly rent for public sector occupations in Chesterfield County</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Occupation </th>
   <th style="text-align:right;"> Maximum monthly rent </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Planners </td>
   <td style="text-align:right;"> $1,655.05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Police officers </td>
   <td style="text-align:right;"> $1,486.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CCPS teachers </td>
   <td style="text-align:right;"> $1,373.42 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Firefighters </td>
   <td style="text-align:right;"> $1,335.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Emergency communications officers </td>
   <td style="text-align:right;"> $1,104.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Administrative workers </td>
   <td style="text-align:right;"> $1,102.88 </td>
  </tr>
</tbody>
</table>

*Source: CoStar Group, Inc. and Chesterfield County.*

## Takeaways

* Although Chesterfield has a relatively high median household income in the region, many of the county's essential workers are not earning enough to keep up with the housing market.
* Homeownership will be increasingly out-of-reach for many workers if current supply and demand trends continue, and especially if interest rates begin rising.
* The average monthly rent in Chesterfield is approaching $1,500. This will be very unaffordable to most of the county's retail, service, and healthcare service workers.
